use_frameworks!

target 'Lottie-Example' do
  pod 'lottie-ios', :path => '../'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'lottie-ios_Tests' do
    inherit! :search_paths

    
  end
end

target 'Lottie-Example-MacOS' do
  pod 'lottie-ios', :path => '../'
end
